<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>OOP_Labo01.Localization</RootNamespace>
    <NeutralLanguage>ru</NeutralLanguage>
  </PropertyGroup>

</Project>
