<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <NeutralLanguage>ru</NeutralLanguage>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <RootNamespace>OOP_Labo01</RootNamespace>
    <ApplicationIcon />
    <StartupObject>OOP_Labo01.App</StartupObject>
  </PropertyGroup>

</Project>
